# Site settings
author: Sarah Williams
title: 
header-img: img/home-bg.png
email: srwilliams8678@gmail.com
copyright_name: Sarah Williams
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: NerdyAndNatural
github_username:  NerdyAndNatural

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
